version: "3"
services:
  nginx:
    image: nginx:1.14
    env_file:
      - ./.env
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./docker/nginx/:/etc/nginx/conf.d/
      - .:/var/www/html

  frontend:
    image: node:${NODE_VER}
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    ports:
      - ${NODE_PORT}:3000
    env_file:
      - .env
    entrypoint: "npm run ${COMMAND}"
